In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.6.0+cu124


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,7],
                      [4,3]])
MATRIX



tensor([[7, 7],
        [4, 3]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([4, 3])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
 Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
 'Start with random numbers -> look at data-> update random numbers -> look at data ->update random numbers


In [ ]:
# Create a random_tensor of size( 3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3982, 0.3167, 0.3231, 0.2272],
        [0.9754, 0.6094, 0.1268, 0.5314],
        [0.8304, 0.3461, 0.8657, 0.2156]])

In [ ]:
# Create a random tensor similar shape to an image tensor
random_image_size_tensor= torch.rand(size=(224,224,3)) #height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(2,2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype


torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensor like


In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start =0, end=1000, step=77)
one_to_ten




tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Create tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

 **Note:** Tensor datatype is one of the 3 bif  errors you'll run into with Pytorch & DeepLearning
 1. Tensors not right datatype
 2. Tensors not  right shape
 3. Tensors not on th right device
  Precision in computing
  https://en.wikipedia.org/wiki/Precision_(computer_science)


In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # What datatype is the tensor
                               device = "cuda", # What device your tensor on
                               requires_grad= False) # whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from tensors

 1. Tensors not right datatype - to do get datatype from a tenosr , can use 'tenosr.dtype'

 2. Tensors not  right shape = to get shape from a tensor , can use 'tensor.shape'

 3. Tensors not on th right device - to get device from a tensor, can use tensor.device

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9054, 0.8897, 0.3506, 0.5367],
        [0.9955, 0.1369, 0.9576, 0.2562],
        [0.7667, 0.8469, 0.0273, 0.7913]])

In [ ]:
#Find out details of some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9054, 0.8897, 0.3506, 0.5367],
        [0.9955, 0.1369, 0.9576, 0.2562],
        [0.7667, 0.8469, 0.0273, 0.7913]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Matrix Multipication

 two ways of performing multipication in neural networks and deep learning
 1. Element-wise Multipication
 2. Matrix Multipication (dot product)

 There are 2 main rules that performing matrix multipication meeds to satisfy:
 1. The **inner dimensions** should match:
 * '(3,2) @ (3,2)' wont work
 * '(2,3) @ (3,2)' will. work
 2. The resulting matrix has the shape of the **outer dimensions**:
 * '(2,3) @ (3,2)' -> (2,2)
 * '(3,2) @ (2,3)' -> (3,3)

In [ ]:
torch.matmul(torch.rand(2,10), torch.rand(10,2)).shape

torch.Size([2, 2])

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 4, 9])
tensor


tensor([1, 4, 9])

In [ ]:
tensor * 10

tensor([10, 40, 90])

In [ ]:
# Try out pytorch in-built function
torch.mul(tensor, 10)

tensor([10, 40, 90])

In [ ]:
# Element wise multipication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 4, 9]) * tensor([1, 4, 9])
Equals: tensor([ 1, 16, 81])


In [ ]:
# MAtrix Multiplication
torch.matmul(tensor,tensor)


tensor(98)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(98)
CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 3.98 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 41.5 µs


tensor(98)

## One of the most common error in deep learning is shape error

In [ ]:
#Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) #torch.mm is the same as torch.matmul (it's an alias for writing less code for matmul)



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 To fix out tensor issues we can manipulate one of the tensor we use transpose


A **Transpose** switches the axes or dimensions of a given tensor.


In [ ]:
tensor_B.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

### Finding the min, max , mean , sum , etc (tensor aggregation)


In [ ]:
# Create a tensor
x = torch. arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()


(tensor(91), tensor(91))

In [ ]:
# Find the mean

torch.mean(x.type(torch.float32).mean())

tensor(46.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in the tensor that has the minimun value with argmin() -. returns the index position of the target tensot where the minimun value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)



##Reshaping, stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an in input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tenosr
* Unsqueeze - add a '1' dimensions to target a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tenosrs on top of each other
x_stacked = torch.stack([x,x,x,x], dim =1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all dimensions from a target
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze()- adds a single dimension to a target tensor at a specific dim( dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Adding extra dimensions to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape:torch.Size([1, 9])


In [ ]:
# torch.permute - rearange the dimensions of target object in a specified order
x_original = torch.rand(size=(224,224,3)) #[height , width , colour_channels]

# Permute the original tensors to rearange the axis (or dim ) order
x_permuted = x_original.permute(2,0,1) #[colour_channels, height, width]
print(f"Original Shape: {x_original.shape}")
print(f"Permuted Shape: {x_permuted.shape}")

Original Shape: torch.Size([224, 224, 3])
Permuted Shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]=21212
x_original[0,0,0],x_permuted[0,0,0]


(tensor(21212.), tensor(21212.))

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy.

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on middle bracket
x[0][0]

tensor([4, 5, 6])

In [ ]:
# Lets index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
 # You can also use ":" to select "all" of a target dimension
 x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]


tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimensions but onlt the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
 # Index on x to return 9
 print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:,:,2])



tensor(9)
tensor([[3, 6, 9]])


In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Pytorch tensors & Numpy

Numpy is a popular scientific Pythin numerical computing library.
And because of this , Pytorch has functionality to interact with it .

* Data in Numpy , want in Pytorch tenosr -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.tensor.numpy()

In [ ]:
#n Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warining: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value of array, what will this do to 'tenosr'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor , what happens to numpy_tensor

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
In short how a neural networks learns:
`start with random numbers -> tensor operations -> update random nnumbers to try and make then of data -> again -> again ..`


To reduce the randomness in neural network and pytorch the concept of **random seed** .

 Essentially what random seeds does is " flavor" the randomness



In [ ]:
import torch
# Create two random tensors

tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)


tensor([[0.2768, 0.3200, 0.5459, 0.6115],
        [0.4062, 0.8656, 0.8538, 0.6390],
        [0.8388, 0.4108, 0.8129, 0.5846]])
tensor([[0.0650, 0.6895, 0.1451, 0.8859],
        [0.4295, 0.9603, 0.4601, 0.8894],
        [0.0074, 0.3423, 0.8782, 0.4296]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
 # Lets make some random but reproducable tensors

import torch


#Set the random seed

RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducbility:
*
*

## Running Tenosrs and Pytorch objects on the GPUs (and making faster computation)

GPus= faster computation on numbers , tahanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunkydory(good)

#### 1. Getting a GPU
1. Easiest - Use Google Collab (options to upgrade)
2. Use your own GPU(Purchase a setup and requires investions )
3. Use collab computing - GCP, AWS, Azure, these services allow you to remt computers on the clous and access them




### 2. Check for GPU access with pytorch

In [ ]:
# Check for GpU acccess with Pytorch

import torch
torch.cuda.is_available()

True

For Pytorch since it is capable of running compute on the GPU or CPU, its best practice to setup device agnostic code.

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of device
torch.cuda.device_count()

1

## Putting Tensors (and models ) on th GPU

Reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor(default on the CPU)

tensor = torch.tensor([1,2,3], device = "cpu")

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors back to the CPU

In [ ]:
# If tensor is on GPU, cant transform it to NumPy
tensor_on_gpu.numpy()


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the GPU tensor with NumPy issue, we can first set it ti the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises  and Extra Curriculum


In [ ]:
# 2.Creating a random tensor (7,7)
import torch

tensor_rand =torch.rand(size=(7,7))
tensor_rand, tensor_rand.shape

(tensor([[0.5101, 0.1460, 0.8175, 0.5985, 0.2834, 0.2103, 0.6638],
         [0.3803, 0.5955, 0.5470, 0.5622, 0.4308, 0.4020, 0.3828],
         [0.6928, 0.1777, 0.5117, 0.2968, 0.0248, 0.6407, 0.6541],
         [0.9449, 0.8285, 0.9894, 0.1071, 0.0648, 0.6555, 0.7450],
         [0.7203, 0.1707, 0.8913, 0.0654, 0.6332, 0.3086, 0.3201],
         [0.8951, 0.9325, 0.6941, 0.7241, 0.5195, 0.1934, 0.6304],
         [0.9300, 0.7095, 0.0515, 0.3947, 0.6595, 0.4078, 0.3445]]),
 torch.Size([7, 7]))

In [ ]:
# 3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1,7) (hint : you may have to teanspose the second tensor)

tensor_A = torch.rand(1,7)

tensor_B=torch.mm(tensor_rand, tensor_A.T)
tensor_B, tensor_B.shape

(tensor([[2.1785],
         [1.8273],
         [2.0691],
         [2.7349],
         [1.9437],
         [2.6868],
         [1.9305]]),
 torch.Size([7, 1]))

In [ ]:
#4. Set the random seed to 0 and do exercise 2 & 3 over again
import torch

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)
print(f"Creating a random tensor:{tensor_A}")

print(f"Matrix Multiplication on tensor:{torch.mm(tensor_A, tensor_B.T)}")


Creating a random tensor:tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Matrix Multiplication on tensor:tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [ ]:
# 5.Create two random tensors of shape(2,3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

import torch

#Set a random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check the access to GPU

device ="cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:{device}")

#Creating two random tensors

tensor_A = torch.rand(2,3).to(device)
tensor_B = torch.rand(2,3).to(device)
tensor_A ,tensor_B

Device:cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [ ]:
#6. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.mm(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [ ]:
#7.Find the max
max = torch.max(tensor_C)


# Find the min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
#  Find the maximum and minimum index values of the output of 7.

import torch

arg_max = torch.argmax(tensor_C)
arg_min = torch.argmin(tensor_C)

print(arg_max), print(arg_min)


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


(None, None)

In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

import torch
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
X = torch.rand(1, 1, 1, 10 )
Y = X.squeeze()
print(X, X.shape)
print(Y,Y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
